[package]
name = "mangadex-scraper"
version = "0.2.2"
authors = ["dyedquartz <dyedquartz@gmail.com>"]
edition = "2018"
description = "scrapes manga off of mangadex.org"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dyedquartz/mangadex-scraper"
readme = "README.md"

[dependencies]
clap = "2.33"
reqwest = "0.9"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
zip = "0.5"
